### ISSUE TITLE
Allow other data types than FILE

### ISSUE THREAD

**Issue by vpavlin** [codex-storage/codex-js#6]
[`upload`](https://github.com/codex-storage/codex-js/blob/master/src/data/data.ts#L60) method assumes the data will be a `FILE`, but a user of the SDK might want to upload generally anything - `blob`, `Uint8Array`, `string`...

Since Codex itself does not work with files, but simply with a stream of bytes, the SDK should accept other types - or at least some JS alternative to `bytes`

**Comment by 2-towns** [comment]
The `upload` method is accepting now the same type as the `send` method of `XMLHttpRequest` so `Document | XMLHttpRequestBodyInit`. 

Please update to version 0.0.12.
