### ISSUE TITLE
Incorrect URL for /connect endpoint

### ISSUE THREAD

**Issue by vpavlin** [codex-storage/codex-js#7]
When I tried to use the `node.connect()` method, the URL generated ended up as

```
...api/codex/v1/connect/16Uiu2HAmCwmepfRARSyWnSMAzUmGfkMr5pvvDC7dKRGVjTNSJBpz?/ip4/178.213.45.235/tcp/8070
```

i.e missing `addrs=` in the query

**Comment by 2-towns** [comment]
Can you try with version 0.0.13 ?

**Comment by vpavlin** [comment]
Seems to work perfectly!
